trigger:
- main

pool:
  name: 'selfhosted'

variables:
  imageName: 'docker-hello-world-spring-boot'

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'clean install'

- task: Maven@3
  displayName: 'Maven Test'
  inputs:
    goals: 'test'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    #containerRegistry: '<your-container-registry-service-connection>'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  displayName: 'Install Trivy'

- task: Trivy@2
  displayName: 'Trivy Scan'
  inputs:
    command: 'image'
    imageName: '$(imageName):$(Build.BuildId)'
