trigger:
- main

pool:
  name: 'selfhosted'

variables:
- group: javapoc  # Link to the 'javapoc' Variable Group

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: SonarQubePrepare@7
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: 'awssonarserver'  # Replace with your SonarQube service connection name
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(sonarProjectKey)'
    cliProjectName: '$(sonarProjectName)'
    cliSources: '.'
    extraProperties: |
      sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

- task: Maven@3
  displayName: 'Maven Build and SonarQube Analysis'
  inputs:
    goals: 'clean install sonar:sonar'
    options: '-DskipTests -Dsonar.projectKey=$(sonarProjectKey) -Dsonar.projectName=$(sonarProjectName) -Dsonar.host.url=$(sonarHostUrl) -Dsonar.login=$(sonarLogin)'

- task: SonarQubePublish@7
  displayName: 'Publish Quality Gate Result'
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $(imageName):$(Build.BuildId)
  displayName: 'Scan Docker image with Trivy'
