trigger:
- main

pool:
  name: 'selfhosted'

variables:
- group: javapoc  # Link to the 'javapoc' Variable Group

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'clean install'

- task: Maven@3
  displayName: 'Run SonarQube Scanner via Maven'
  inputs:
    goals: 'sonar:sonar'
    options: >
      -Dsonar.projectKey=$(sonarProjectKey)
      -Dsonar.projectName=$(sonarProjectName)
      -Dsonar.host.url=$(sonarHostUrl)
      -Dsonar.login=$(sonarLogin)

- task: Maven@3
  displayName: 'Maven Test'
  inputs:
    goals: 'test'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $(imageName):$(Build.BuildId)
  displayName: 'Scan Docker image with Trivy'
