trigger:
- main

pool:
  name: 'selfhosted'

variables:
- group: javapoc  # Link to the 'javapoc' Variable Group

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'clean install'
    options: '-DskipTests'

- task: Maven@3
  displayName: 'Run Tests and Generate Code Coverage Report'
  inputs:
    goals: 'test'
    options: '-Pcoverage'

- task: SonarQubePrepare@5
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: 'awssonarserver'  # Replace with your SonarQube service connection name
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(sonarProjectKey)'
    cliProjectName: '$(sonarProjectName)'
    cliSources: '.'
    extraProperties: |
      sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

#- task: SonarQubeAnalyze@5
  #displayName: 'Run SonarQube Analysis'

#- task: SonarQubePublish@5
  #displayName: 'Publish Quality Gate Result'
  #inputs:
    #pollingTimeoutSec: '300'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $(imageName):$(Build.BuildId)
  displayName: 'Scan Docker image with Trivy'
