trigger:
- main

pool:
  name: 'selfhosted'

variables:
- group: javapoc  # Link to the 'javapoc' Variable Group

steps:
- task: JavaToolInstaller@0
  displayName: 'Install Java 11'
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- checkout: self
  displayName: 'Checkout source code'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'clean install'
    options: '-DskipTests'

- task: Maven@3
  displayName: 'Run Tests and Generate Code Coverage Report'
  inputs:
    goals: 'test'
    options: '-Pcoverage'

- task: SonarQubePrepare@5
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: 'awssonarserver'  # Your SonarQube service connection name
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(sonarProjectKey)'
    cliProjectName: '$(sonarProjectName)'
    cliSources: '.'
    extraProperties: |
      sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      sonar.host.url=http://34.207.231.98:8080  # Use http if your server is not configured for https
      sonar.login=$(sonarLogin)
      sonar.password=$(sonarPassword)
      sonar.verbose=true

- task: Maven@3
  displayName: 'Maven Build with SonarQube Analysis'
  inputs:
    goals: 'clean install sonar:sonar'
    options: '-DskipTests'

- task: SonarQubePublish@5
  displayName: 'Publish Quality Gate Result'
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $(imageName):$(Build.BuildId)
  displayName: 'Scan Docker image with Trivy'
