trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'docker-hello-world-spring-boot'

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    #containerRegistry: '<your-container-registry-service-connection>'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
