trigger:
- main

pool:
  name: 'selfhosted'

variables:
  imageName: 'docker-hello-world-spring-boot'

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'clean install'

- task: Maven@3
  displayName: 'Maven Test'
  inputs:
    goals: 'test'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    #containerRegistry: '<your-container-registry-service-connection>'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $(imageName):$(Build.BuildId)
  displayName: 'Scan Docker image with Trivy'

#- task: Docker@2
  #displayName: 'Push Docker image'
  #inputs:
    #containerRegistry: '<your-container-registry-service-connection>'
    #repository: '$(imageName)'
    #command: 'push'
    #tags: |
      #$(Build.BuildId)
