trigger:
- main

pool:
  name: 'selfhosted'

variables:
- group: javapoc  # Link to the 'javapoc' Variable Group

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'awssonarserver'
    scannerMode: 'other'


- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: '/usr/lib/jvm/java-17-amazon-corretto.aarch64'
    jdkArchitectureOption: 'x64'
    goals: 'clean install sonar:sonar'
