trigger:
- main

pool:
  name: 'selfhosted'

variables:
- group: javapoc  # Link to the 'javapoc' Variable Group

steps:
- checkout: self
  displayName: 'Checkout source code'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'awssonarserver'
    scannerMode: 'other'

- task: Maven@3
  displayName: 'Build with Maven'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: '/usr/lib/jvm/java-17-amazon-corretto.aarch64'
    jdkArchitectureOption: 'x64'
    goals: 'clean install sonar:sonar'

- task: Maven@3
  displayName: 'Run Tests and Generate Code Coverage Report'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: '/usr/lib/jvm/java-17-amazon-corretto.aarch64'
    jdkArchitectureOption: 'x64'
    goals: 'test'
    options: '-Pcoverage'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

- script: |
    previous_build_id=$(docker images --format "{{.Tag}}" $(imageName) | grep -v latest | sort -r | head -n 1)
    if [ -n "$previous_build_id" ]; then
      docker rmi $(imageName):$previous_build_id
    fi
  displayName: 'Remove previous Docker image'

- script: |
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $(imageName):latest
  displayName: 'Scan Docker image with Trivy'
